# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazycopilot < Formula
  desc "A lazy copilot for your projects"
  homepage ""
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mr687/lazycopilot/releases/download/v1.0.0/lazycopilot_Darwin_x86_64.tar.gz"
      sha256 "4e11b719f239c64ce7a6d73b43b44fff73be75ed04e3a2ca0c28539c49b0cd96"

      def install
        bin.install "lazycopilot"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mr687/lazycopilot/releases/download/v1.0.0/lazycopilot_Darwin_arm64.tar.gz"
      sha256 "e070699b15488fdcd27fdf02ce1d6b5ee9e39f7632f1836fffcc8f627f984ba2"

      def install
        bin.install "lazycopilot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mr687/lazycopilot/releases/download/v1.0.0/lazycopilot_Linux_x86_64.tar.gz"
        sha256 "80cd3ac1dafda54b85271b409329cfbdd450960181c201cd4a0d903952a5395f"

        def install
          bin.install "lazycopilot"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mr687/lazycopilot/releases/download/v1.0.0/lazycopilot_Linux_arm64.tar.gz"
        sha256 "7d2ae79db732dc33af5eb55a54f20de56d012fb799965d07b368c7a321b37167"

        def install
          bin.install "lazycopilot"
        end
      end
    end
  end

  test do
    system "#{bin}/lazycopilot --version"
  end
end
