# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazycopilot < Formula
  desc "A lazy copilot for your projects"
  homepage ""
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mr687/lazycopilot/releases/download/v1.1.0/lazycopilot_Darwin_x86_64.tar.gz"
      sha256 "41a6feaf6202e3003430dd26c1899cfea9d0ea54db8d86f6d54108f07a4f8eea"

      def install
        bin.install "lazycopilot"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mr687/lazycopilot/releases/download/v1.1.0/lazycopilot_Darwin_arm64.tar.gz"
      sha256 "9c70085385db40fca459cbf6eb4f2c7c54d46c203264ce1cf3b3a3b475cdb179"

      def install
        bin.install "lazycopilot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mr687/lazycopilot/releases/download/v1.1.0/lazycopilot_Linux_x86_64.tar.gz"
        sha256 "7297c967085ad8e98c26b85ff81b784f640a86526083c08446972fedc55d419c"

        def install
          bin.install "lazycopilot"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mr687/lazycopilot/releases/download/v1.1.0/lazycopilot_Linux_arm64.tar.gz"
        sha256 "6c91207e799751719b2a5acfad0dd37f2131a9a52c75d66971881be9457a75c2"

        def install
          bin.install "lazycopilot"
        end
      end
    end
  end

  test do
    system "#{bin}/lazycopilot --version"
  end
end
